### ISSUE TITLE
Align the gem versioning with bootstrap-tokenfield

### ISSUE THREAD

**Issue by zedtux** [icicletech/bootstrap-tokenfield-rails#6]
It's more easy for people to select the version of the wrapping gem when its conversioning is the same as the wrapped item.

This would lead you to have `bootstrap-tokenfield-rails` version 0.12.1 packaging the version 0.12.1 of `bootstrap-tokenfield`. You also then can remove the **Changelog** section of your `README.md` file.

**Comment by zedtux** [comment]
Also use tags in order to do this which will creates releases in Github. You can have a look at a lot of existing gems but here is one of mine : https://github.com/YourCursus/switchery-rails

**Comment by zedtux** [comment]
You can also have a look at my `Rakefile` where I've created a task to download the given version of the library.
So that the workflow is the following:
 - A new version is available
 - You update the `version.rb` of your gem
 - You then run the rake task which will download the right Javascript and CSS files
 - Then you commit, tag, package and push

**Comment by akashdevaraju** [comment]
@zedtux Thanks a bunch for your input. Will be improving the workflow and incorporating your suggestions.

**Comment by SrikalaB** [comment]
@zedtux Thanks! Incorporated your suggestions in #8 .

**Comment by akashdevaraju** [comment]
Resolved, closing issue @zedtux @SrikalaB

**Comment by zedtux** [comment]
Nice @akashdevaraju. Just for you, in order to help you, you can refer to a Github issue in your commit message which will then show up the commit on the issue. You can do so with a commit message like the following: "Align gem version (Fixes #6)". It would even close the issue automatically for you ;)

**Comment by akashdevaraju** [comment]
That's cool, thanks for the protip :+1: will use in the future @zedtux

**Comment by zedtux** [comment]
You're welcome :)
