### ISSUE TITLE
Add pkg/ to the .gitignore file

### ISSUE THREAD

**Issue by zedtux** [icicletech/bootstrap-tokenfield-rails#7]
As of now you're including binary files in your Github repo (the `pkg` folder created by Bundler when using the build or release Rake task).

This is not critical but not clean. Also it contains first versions which doesn't make sense :)

**Comment by akashdevaraju** [comment]
Thanks very much for that :) will make the changes and push.

**Comment by akashdevaraju** [comment]
Resolved with c34f15c56164e85d709906ad55a7e09ee4cc3bd4
